version: "3"
services:
  db:
    image: mysql:8
    restart: always
    container_name: db_mysql
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - dev
networks:
  dev:
volumes:
  my-db:
