name: Shop CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            whoami || echo
            git pull origin main
            composer install
            php bin/console cache:clear
            php bin/console doctrine:schema:update --force
            php bin/console cache:clear
            php bin/console cache:warmup
